// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetLink.API.Data;

#nullable disable

namespace NetLink.API.Migrations
{
    [DbContext(typeof(NetLinkDbContext))]
    [Migration("20240310211117_RemovedUnvatedRelations")]
    partial class RemovedUnvatedRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetLink.API.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DevToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("NetLink.API.Models.DeveloperUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("EndUserId");

                    b.ToTable("DeveloperUsers");
                });

            modelBuilder.Entity("NetLink.API.Models.EndUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("EndUsers");
                });

            modelBuilder.Entity("NetLink.API.Models.EndUserSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EndUserId");

                    b.HasIndex("SensorId");

                    b.ToTable("EndUserSensors");
                });

            modelBuilder.Entity("NetLink.API.Models.EndUserSensorGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SensorGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EndUserId");

                    b.HasIndex("SensorGroupId");

                    b.ToTable("EndUserSensorGroups");
                });

            modelBuilder.Entity("NetLink.API.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SensorGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SensorGroupId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("NetLink.API.Models.SensorGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EndUserId");

                    b.ToTable("SensorGroups");
                });

            modelBuilder.Entity("NetLink.API.Models.DeveloperUser", b =>
                {
                    b.HasOne("NetLink.API.Models.Developer", "Developer")
                        .WithMany("DeveloperUsers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetLink.API.Models.EndUser", "EndUser")
                        .WithMany("DeveloperUsers")
                        .HasForeignKey("EndUserId");

                    b.Navigation("Developer");

                    b.Navigation("EndUser");
                });

            modelBuilder.Entity("NetLink.API.Models.EndUserSensor", b =>
                {
                    b.HasOne("NetLink.API.Models.EndUser", "EndUser")
                        .WithMany("EndUserSensors")
                        .HasForeignKey("EndUserId");

                    b.HasOne("NetLink.API.Models.Sensor", "Sensor")
                        .WithMany("EndUserSensors")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndUser");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("NetLink.API.Models.EndUserSensorGroup", b =>
                {
                    b.HasOne("NetLink.API.Models.EndUser", "EndUser")
                        .WithMany("EndUserSensorGroups")
                        .HasForeignKey("EndUserId");

                    b.HasOne("NetLink.API.Models.SensorGroup", "SensorGroup")
                        .WithMany("EndUserSensorGroups")
                        .HasForeignKey("SensorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndUser");

                    b.Navigation("SensorGroup");
                });

            modelBuilder.Entity("NetLink.API.Models.Sensor", b =>
                {
                    b.HasOne("NetLink.API.Models.SensorGroup", "SensorGroup")
                        .WithMany()
                        .HasForeignKey("SensorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorGroup");
                });

            modelBuilder.Entity("NetLink.API.Models.SensorGroup", b =>
                {
                    b.HasOne("NetLink.API.Models.EndUser", "EndUser")
                        .WithMany()
                        .HasForeignKey("EndUserId");

                    b.Navigation("EndUser");
                });

            modelBuilder.Entity("NetLink.API.Models.Developer", b =>
                {
                    b.Navigation("DeveloperUsers");
                });

            modelBuilder.Entity("NetLink.API.Models.EndUser", b =>
                {
                    b.Navigation("DeveloperUsers");

                    b.Navigation("EndUserSensorGroups");

                    b.Navigation("EndUserSensors");
                });

            modelBuilder.Entity("NetLink.API.Models.Sensor", b =>
                {
                    b.Navigation("EndUserSensors");
                });

            modelBuilder.Entity("NetLink.API.Models.SensorGroup", b =>
                {
                    b.Navigation("EndUserSensorGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
